# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
  # see:https://github.com/Lightning-AI/pytorch-lightning/issues/15283 problems